### PR TITLE
Feature webpack - review

### PR DESCRIPTION
**Pull request by paulo-techie**
- Create a bare-bones homepage for a restaurant. Include an image, headline, and some copy about how wonderful the restaurant is. 
- Create page elements using JavaScript only, e.g. by appending each new element to div#content once the page is first loaded. Leave only the '<html>, <body>, and <div id="content">' tags.
- Set up your restaurant site to use tabbed browsing to access the Contact and Menu pages.
- Put the contents of each ‘tab’ inside of its own module. Each module will export a function that creates a div element, adds the appropriate content and styles to that element and then appends it to the DOM.
- Write the tab-switching logic inside of index.js. You should have event listeners for each tab that wipes out the current contents and then runs the correct ‘tab module’ to populate it again.
- The content pages should be created in a separate files and the 'webpack' utility applied to build and merge the pages.

### CODE REVIEW

**Review by Temmarie — COMMENTED** [review]
## STATUS: INVALID! :exclamation:
### Hi @paulo-techie    ! :wave: :wave:

#### Hello there, good job completing this project, I however have to mark this project as invalid because you have not followed GitFlow. Please work with Git Flow: production master branch + main develop branch + Pull Requests from feature branches to the develop ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/git_flow_requirement.png) from[ Pathwright](https://microverse.pathwright.com/library/javascript-module-v-10/166782/path/step/97634928/))

_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by paulo-techie** [comment]
> ## STATUS: INVALID! ❗
> ### Hi @paulo-techie ! 👋 👋
> #### Hello there, good job completing this project, I however have to mark this project as invalid because you have not followed GitFlow. Please work with Git Flow: production master branch + main develop branch + Pull Requests from feature branches to the develop ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/git_flow_requirement.png) from[ Pathwright](https://microverse.pathwright.com/library/javascript-module-v-10/166782/path/step/97634928/))
> _Feel free to reach me on slack for any inquiries about this review._ 😉
> __Grace Tamara Ekunola __
> [GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

Thanks for quick response. Changes made to branch to align to Git Flow.

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
## **Changes Required 🛑♻**

<hr>

Hello Paulo😊
Great work and effort you made into this project so far 💯 

### **Highlights 🎉**

- Well-configured Linter 🥇 
- Descriptive PR summary 🥇 
- Followed the GIT Guidelines 🥇 
- Good code division to keep it clean 🥇 

However, there is always room for improvement. Kindly consider my comments below 👍

### **To Improve ⚠**

**README**

- [ ] Please fix the "Issues Page" and the "MIT License" Page in your README file because they seem to be broken.
- [ ] Please write a proper "How to use" section to make it easy for non-programmers to install your app locally. Ex: CLIs like ```npm install``` and ```npm run build``` which we will cover in a moment.

**Code**

- [ ] Please make sure that each loaded (tabbed) page has its own module that will exports a function that creates a div with that tabbed page. Currently, they're all just functions inside the bigger module **loadPage** that's been exported. Kindly look at the image below.
tab_requirement

- [ ] Please make sure that the dis directory has a file called index.html that built by an npm command line. Take a look at the image below
dist_requirement

- [ ] Please add the proper scripts at JSON package file to help to build the app's code environment.
scripts_requirement

Ex:
```
"scripts": {
    "dev": "webpack --mode development", // for building into development mode
    "build": "webpack --mode production", // for building into production mode
    "start": "webpack serve" // OPTIONAL // for starting a local live server
  }
```
### **Nice to have 😊🙏**

- It'd be awesome if you manage to deploy your app on a live demo link and include the link in the README file for future easier access.

<hr>

Good luck and happy coding 👨‍💻💻
Please feel free to contact me on Slack with the name "Mahmoud Bakr" if you got any sort of question.

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED ♻️ 🛑 

Hello @paulo-techie 👋🏿 . Great work making some of the changes requested by the previous reviewer. Great work separating your code into modules 👏🏿 . However, kindly improve on the following ⬇️ 

- [ ] Just like stated by the previous reviewer,  Please write a proper "How to use" section to make it easy for non-programmers to install your app locally. Ex: CLIs like npm install and npm run build. You can add this to your readme file.


**[OPTIONAL]**

- [ ] Kindly note, always capitalize the first letter in your commit messages. This will make your project more professional.

### if you have any question, kindly reach me via slack @peterrobert

### HAPPY CODING 💻

**Review by peterrobert — APPROVED** [review]
### APPROVED 💯 
Hello, @paulo-techie  great work making the changes as requested. On to the next project. Happy coding 💻

**Pull request merged**
